spring:
  banner:
    charset: UTF-8
    location: classpath:banner.txt
  servlet:
    multipart:
      max-file-size: 200MB
      max-request-size: 200MB
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: false
    hibernate:
      #更新或者创建数据库表结构(第一次启动请设置为update)
      ddl-auto: none
  influx:
    user: cwl
    # 你的数据库url
    url: http://192.168.49.129:8086
    password: 1234
    mapper-location: top.rslly.iot.dao
    dataBaseName: data
    retention: autogen     #保存策略
  datasource:
    username: cwliot1.8
    url: jdbc:mysql://192.168.49.129:3306/cwliot1.8?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    # 输入你自己的mysql密码,该密码为随机生成
    password: "DMKRjBbHCiPAyAdn"
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      # 下面为连接池的补充设置，应用到上面所有数据源中
      # 初始化大小，最小，最大
      initial-size: 5
      min-idle: 5
      max-active: 20
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      time-between-eviction-runs-millis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      min-evictable-idle-time-millis: 300000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的 Filter，去掉后监控界面 SQL 无法统计，wall 用于防火墙   日志 log4j
      # filters: stat,wall,log4j   #导入了log4j
      use-global-data-source-stat: true
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connect-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: admin
        login-password: 123456
  redis:
    host: 192.168.49.129
    password: 1234
    port: 6379
    timeout: 1000
  mail:
    host: smtp.126.com
    port: 465
    protocol: smtps
    username: ruanzhen1234@126.com
    password: XXX
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl: true
  thymeleaf:
    cache: true
    mode: html
    prefix: classpath:/templates/
    encoding: UTF-8
    servlet:
      content-type: text/html
grpc:
  server:
    port: 9090
mqtt:
  Host: tcp://192.168.49.129:1883
  username: hello
  password: 1234
wx:
  debug: true
  appid: XXXXXX
  appsecret: XXXXXX
  templateUrl: XXXXX
  alarmTemplateId: XXXXXX
  micro:
    appid: XXXXXX
    appsecret: XXXXXX
    ToUserName: XXXXXX
    appid2: XXXXXX
    ToUserName2: XXXXXX
    appsecret2: XXXXXX
  msg:
    token: XXXXXX
storage:
  database: influxdb
js:
  local:
    use_js_sandbox: true
    monitor_thread_pool_size: 4
    max_cpu_time: 300000
    max_black_list_duration_sec: 60
    maxInvokeRequestsTimeout: 5
    js_thread_pool_size: 50
ota:
  bin:
    path: D://temp-rainy//
    url: http://127.0.0.1:8080/api/v2/micro/
  xiaozhi:
    url: ws://127.0.0.1:8080
    version: 1.9.2
rag:
  embedding_modelName: bge-small-zh-v1.5-quantized
  knowledge_chat_embeddingStore_url: http://localhost:8000
weather:
  key: XXX
ai:
  chromeDrive-path: XXX
  chrome-path: XXX
  audio-tmp-path: D://temp-music//
  audio-temp-url: https://XXX.com
  vision-explain-url: http://127.0.0.1:8080/api/v2/vision/explain
  vision-model: silicon-Qwen2.5-vl-32B-Instruct
  glm-key: XXX
  deepSeek-key: XXX
  siliconFlow-Key: XXX
  uniApi-Key: XXX
  dashscope-key: XXX
  robot-name: 小创
  team-name: 创万联
  agent-epoch-limit: 5
  chatTool-llm: silicon-Qwen3-Next-80B-A3B-Instruct
  chatTool-speedUp: true
  emotionTool-llm: silicon-Qwen3-30B-A3B-think-32
  memoryTool-llm: silicon-Qwen2.5-14B-Instruct
  classifierTool-llm: silicon-Qwen3-Next-80B-A3B-Instruct
  classifierTool-speedUp: true
  controlTool-llm: silicon-Qwen3-Next-80B-A3B-Instruct
  musicTool-llm: silicon-Qwen2.5-7B-Instruct
  productRoleTool-llm: silicon-Qwen2.5-7B-Instruct
  weatherTool-llm: silicon-Qwen3-30B-A3B
  wxBoundProductTool-llm: silicon-Qwen2.5-7B-Instruct
  wxProductActiveTool-llm: silicon-Qwen2.5-7B-Instruct
  scheduleTool-llm: silicon-Qwen3-Next-80B-A3B-Instruct
  searchTool-llm: silicon-Qwen2.5-7B-Instruct
  agent-llm: silicon-Qwen3-Next-80B-A3B-Instruct
  mcp:
    agent-llm: silicon-Qwen3-Next-80B-A3B-Instruct
    agent-epoch-limit: 5
emq:
  api:
    url: http://192.168.49.129:18083/api/v5/clients
    key: XXX
    secret: XXX